{{- if .Values.pvc.enabled  -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default (printf "%s" (include "generic-chart.fullname" .)) | quote }}
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.pvc.annotations .Values.additionalAnnotations }}
  {{- with .Values.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.pvc.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with.Values.pvc.spec }}
spec:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}