{{- if .Values.secret.enabled -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.name | default (printf "%s" (include "generic-chart.fullname" .)) | quote }}
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.secret.annotations }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.secret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type }}
{{- with .Values.secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
