{{- if .Values.service.enabled  -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (printf "%s" (include "generic-chart.fullname" .)) | quote }}
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.service.annotations }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- $ports := include "service.servicePortsConfig" . }}
  {{- if $ports }}
  ports:
    {{- $ports | nindent 4}}
  {{- end }}
  {{- if .Values.service.selector }}
  {{- with .Values.service.selector }}
  selector:
    {{- toYaml . | default (include "generic-chart.selectorLabels" .) | nindent 4 }}
  {{- end }}
  {{ else }}
  selector:
    {{- include "generic-chart.selectorLabels" . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.serviceGeneric.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceGeneric.name | default (printf "%s" (include "generic-chart.fullname" .)) | quote }}
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.serviceGeneric.annotations }}
  {{- with .Values.serviceGeneric.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.serviceGeneric.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with.Values.serviceGeneric.spec }}
spec:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
