name: go-server CI

on:
  push:
#    branches: [ main ]
    paths:
      - 'go-server/*'
  pull_request:
#    branches: [ main ]
    paths:
      - 'go-server/*'
jobs:
  docker-go:
    name: build and push go-server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
#    - name: Build the Docker image
#      run: docker build go-server/. --file go-server/Dockerfile --tag karlyan/go-server:latest
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: ./go-server/
        file: ./go-server/Dockerfile
        push: true
        tags: karlyan/go-server:latest
