name: Docker Image CI

on:
  push:
#    branches: [ main ]
    paths:
      - 'python-server/*'
  pull_request:
#    branches: [ main ]
    paths:
      - 'python-server/*'
jobs:
  docker-go:
    name: build and push go-server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./go-server/
        file: ./go-server/Dockerfile
        push: true
        tags: karlyan/python-server:latest