name: go-server CI

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'The pushed image tag name'
        required: true
        default: 'latest'

jobs:
  docker-go:
    name: build and push go-server
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: ./go-server/
        file: ./go-server/Dockerfile
        push: true
        tags: karlyan/go-server:${{ github.event.inputs.tagName }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
